seed: 42

classes:
  class_list_path: data/classes.txt

audio:
  sample_rate: 32000
  window_seconds: 5.0
  shift_seconds: 2.5
  n_fft: 2048
  win_length: 2048
  hop_length: 768
  n_mels: 192
  f_min: 50
  f_max: 15000

model:
  backbone: tf_efficientnetv2_s.in21k
  num_classes: 206
  pretrained: true

train:
  batch_size: 16
  epochs: 10
  learning_rate: 0.0005
  weight_decay: 0.00001
  use_focal_loss: true
  focal_gamma: 2.0
  label_smoothing: 0.005
  student_hard_loss_weight: 0.6

ensemble:
  model_limit: null
  regular_prefix: model_
  shifted_prefix: model2_
  regular_weight: 0.50
  shifted_left_weight: 0.25
  shifted_right_weight: 0.25
  smoothing_weight: 0.10
  aggregate_method: max

evaluation:
  threshold: 0.5
  search_threshold: true
  max_files: null
